# Analysing nothing and random game commands

In [1]:
import numpy as np

In [2]:
def load_npz(data_path, m):
    
    path = data_path + "match_" + str(m) + "/npz/"

    actions = np.load(path + 'actions.npz')
    lifes = np.load(path + 'lifes.npz')
    frames = np.load(path + 'frames.npz')
    rewards = np.load(path + 'rewards.npz')

    arr_actions = actions.f.arr_0
    arr_lifes = lifes.f.arr_0
    arr_frames = frames.f.arr_0
    arr_rewards = rewards.f.arr_0

    print("Successfully loaded NPZ.")

    return arr_actions.shape[0], arr_frames, arr_actions, arr_rewards, arr_lifes

In [3]:
data_path = r"data/"

In [43]:
def match_info(data_path, match):
    num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
    (unique, counts) = np.unique(actions, return_counts=True)
    action_frequencies = np.asarray((unique, counts))
    
    print("match", match)
    print("number of frames:", num_of_frames)
    print("number of actions:", len(actions))
    print("action frequencies:")
    print(action_frequencies)
    
    return frames, actions

In [49]:
def get_acc(actions, predicted):
    return (actions == predicted).sum()/len(actions)

## Created game

### Game doing nothing

1000
#### Position
200/200
#### Km
35

### Game random

#### Position
200/200
#### Km
40

## Match accuracies

In [88]:
match = 1

frames, actions = match_info(data_path, match)
actions = actions[0:1000]

predicted = np.zeros(1000,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=1000)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 1
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [1923 1021  450  642   40   56   60  125  183]]
nothing: 0.489
random: 0.108


In [85]:
actions.shape

(1000,)

In [87]:
predicted.shape

(4500,)

First 1000
#### Position
135
#### Km
354

In [60]:
match = 2

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 2
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2339  669  686  498   37   34   25   97  115]]
nothing: 0.5197777777777778
random: 0.10622222222222222


In [61]:
match = 3

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 3
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2654  375  580  743   24   13   21   22   68]]
nothing: 0.5897777777777777
random: 0.09644444444444444


In [62]:
match = 4

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 4
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2164  930  677  527   31   23   31   66   51]]
nothing: 0.48088888888888887
random: 0.11533333333333333


In [63]:
match = 5

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 5
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2413  714  472  647   81   24   20   48   81]]
nothing: 0.5362222222222223
random: 0.11888888888888889


In [64]:
match = 6

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 6
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [1641 1309  643  416   32   66   60  149  184]]
nothing: 0.36466666666666664
random: 0.11022222222222222


In [70]:
match = 7

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 7
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2341  590  645  652   33   19   43   76  101]]
nothing: 0.5202222222222223
random: 0.10733333333333334


In [72]:
match = 8

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 8
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2674  398  953  401   28    3    4   30    9]]
nothing: 0.5942222222222222
random: 0.11355555555555556


In [75]:
match = 9

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 9
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2752  469  619  524   38   16   10   36   36]]
nothing: 0.6115555555555555
random: 0.108


In [77]:
match = 10

frames, actions = match_info(data_path, match)

predicted = np.zeros(4500,)
print("nothing:", get_acc(actions, predicted))

predicted = np.random.randint(9, size=4500)
print("random:", get_acc(actions, predicted))

Successfully loaded NPZ.
match 10
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2712  465  678  464   27   30   13   88   23]]
nothing: 0.6026666666666667
random: 0.104
