In [1]:
import numpy as np

In [2]:
def load_npz(data_path, m):
    
    path = data_path + "match_" + str(m) + "/npz/"

    actions = np.load(path + 'actions.npz')
    lifes = np.load(path + 'lifes.npz')
    frames = np.load(path + 'frames.npz')
    rewards = np.load(path + 'rewards.npz')

    arr_actions = actions.f.arr_0
    arr_lifes = lifes.f.arr_0
    arr_frames = frames.f.arr_0
    arr_rewards = rewards.f.arr_0

    print("Successfully loaded NPZ.")

    return arr_actions.shape[0], arr_frames, arr_actions, arr_rewards, arr_lifes

In [18]:
data_path = r"data/"

### List of action

0. Não faz nada
1. Acelera
2. Vai para direita
3. Vai para esquerda
4. freio
5. freio para direita
6. freio para esquerda
7. Vai para direira acelerando
8. Vai para esquerda acelerando

### match 45 (jogando)

In [19]:
match = 45

In [20]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [27]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 45
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [1923 1021  450  642   40   56   60  125  183]]


### match 46 (jogando)

In [28]:
match = 46

In [29]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [30]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 46
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2339  669  686  498   37   34   25   97  115]]


### match 47

In [31]:
match = 47

In [32]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [33]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 47
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2654  375  580  743   24   13   21   22   68]]


### match 48

In [34]:
match = 48

In [35]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [36]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 48
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2164  930  677  527   31   23   31   66   51]]


### match 50

In [39]:
match = 50

In [40]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [41]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 50
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2413  714  472  647   81   24   20   48   81]]
