# Analysing splited data

In [1]:
import numpy as np

In [2]:
def load_npz(data_path, m):
    
    path = data_path + "match_" + str(m) + "/npz/"

    actions = np.load(path + 'actions.npz')
    lifes = np.load(path + 'lifes.npz')
    frames = np.load(path + 'frames.npz')
    rewards = np.load(path + 'rewards.npz')

    arr_actions = actions.f.arr_0
    arr_lifes = lifes.f.arr_0
    arr_frames = frames.f.arr_0
    arr_rewards = rewards.f.arr_0

    print("Successfully loaded NPZ.")

    return arr_actions.shape[0], arr_frames, arr_actions, arr_rewards, arr_lifes

In [3]:
data_path = r"data/"

### List of action

0. Não faz nada
1. Acelera
2. Vai para direita
3. Vai para esquerda
4. freio
5. freio para direita
6. freio para esquerda
7. Vai para direira acelerando
8. Vai para esquerda acelerando

### match 0

In [4]:
match = 0

In [5]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [6]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 0
number of frames: 120
number of actions: 120
action frequencies:
[[ 2  3]
 [60 60]]


In [8]:
frames = frames.reshape(120, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)

### match 45 (jogando)

In [55]:
match = 1

In [56]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [57]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 1
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [1923 1021  450  642   40   56   60  125  183]]


In [59]:
frames = frames.reshape(4500, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)

### match 46 (jogando)

In [64]:
match = 2

In [65]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [66]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 2
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2339  669  686  498   37   34   25   97  115]]


In [67]:
frames = frames.reshape(4500, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)

### match 47

In [68]:
match = 3

In [69]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [70]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 3
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2654  375  580  743   24   13   21   22   68]]


In [71]:
frames = frames.reshape(4500, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)

### match 48

In [72]:
match = 4

In [73]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [74]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 4
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2164  930  677  527   31   23   31   66   51]]


In [75]:
frames = frames.reshape(4500, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)

### match 49

In [76]:
match = 5

In [77]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [78]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 5
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [2413  714  472  647   81   24   20   48   81]]


In [79]:
frames = frames.reshape(4500, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)

### match 50

In [80]:
match = 6

In [81]:
num_of_frames, frames, actions, rewards, lifes = load_npz(data_path, match)
(unique, counts) = np.unique(actions, return_counts=True)
action_frequencies = np.asarray((unique, counts))

Successfully loaded NPZ.


In [82]:
print("match", match)
print("number of frames:", num_of_frames)
print("number of actions:", len(actions))
print("action frequencies:")
print(action_frequencies)

match 6
number of frames: 4500
number of actions: 4500
action frequencies:
[[   0    1    2    3    4    5    6    7    8]
 [1641 1309  643  416   32   66   60  149  184]]


In [83]:
frames = frames.reshape(4500, 170, 120)
np.savez_compressed(data_path + f"match_{match}/npz/frames.npz", frames)